/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository.
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => OpenCodePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  port: 14096,
  hostname: "127.0.0.1",
  autoStart: false,
  opencodePath: "opencode",
  projectDirectory: "",
  startupTimeout: 15e3,
  defaultViewLocation: "sidebar",
  installations: [],
  selectedInstallationId: null,
  opencodeConfigPath: "",
  autoInstallEnabled: false,
  checkForUpdates: true
};
var OPENCODE_VIEW_TYPE = "opencode-view";

// src/OpenCodeView.ts
var import_obsidian2 = require("obsidian");

// src/icons.ts
var import_obsidian = require("obsidian");
var OPENCODE_ICON_NAME = "opencode-logo";
var OPENCODE_LOGO_SVG = `<svg viewBox="0 0 24 30" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M18 24H6V12H18V24Z" fill="currentColor" opacity="0.4"/>
  <path d="M18 6H6V24H18V6ZM24 30H0V0H24V30Z" fill="currentColor"/>
</svg>`;
function registerOpenCodeIcons() {
  (0, import_obsidian.addIcon)(OPENCODE_ICON_NAME, OPENCODE_LOGO_SVG);
}

// src/OpenCodeView.ts
var OpenCodeView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.iframeEl = null;
    this.currentState = "stopped";
    this.unsubscribeStateChange = null;
    this.plugin = plugin;
  }
  getViewType() {
    return OPENCODE_VIEW_TYPE;
  }
  getDisplayText() {
    return "OpenCode";
  }
  getIcon() {
    return OPENCODE_ICON_NAME;
  }
  async onOpen() {
    this.contentEl.empty();
    this.contentEl.addClass("opencode-container");
    const installationState = this.plugin.getInstallationState();
    if (installationState === "not-installed") {
      this.renderNotInstalledState();
      return;
    }
    this.unsubscribeStateChange = this.plugin.onProcessStateChange((state) => {
      this.currentState = state;
      this.updateView();
    });
    this.currentState = this.plugin.getProcessState();
    this.updateView();
    if (this.currentState === "stopped") {
      this.plugin.startServer();
    }
  }
  async onClose() {
    if (this.unsubscribeStateChange) {
      this.unsubscribeStateChange();
      this.unsubscribeStateChange = null;
    }
    if (this.iframeEl) {
      this.iframeEl.src = "about:blank";
      this.iframeEl = null;
    }
  }
  updateView() {
    switch (this.currentState) {
      case "stopped":
        this.renderStoppedState();
        break;
      case "starting":
        this.renderStartingState();
        break;
      case "running":
        this.renderRunningState();
        break;
      case "error":
        this.renderErrorState();
        break;
    }
  }
  renderStoppedState() {
    this.contentEl.empty();
    const statusContainer = this.contentEl.createDiv({
      cls: "opencode-status-container"
    });
    const iconEl = statusContainer.createDiv({ cls: "opencode-status-icon" });
    (0, import_obsidian2.setIcon)(iconEl, "power-off");
    statusContainer.createEl("h3", { text: "OpenCode is stopped" });
    statusContainer.createEl("p", {
      text: "Click the button below to start the OpenCode server.",
      cls: "opencode-status-message"
    });
    const startButton = statusContainer.createEl("button", {
      text: "Start OpenCode",
      cls: "mod-cta"
    });
    startButton.addEventListener("click", () => {
      this.plugin.startServer();
    });
  }
  renderStartingState() {
    this.contentEl.empty();
    const statusContainer = this.contentEl.createDiv({
      cls: "opencode-status-container"
    });
    const loadingEl = statusContainer.createDiv({ cls: "opencode-loading" });
    loadingEl.createDiv({ cls: "opencode-spinner" });
    statusContainer.createEl("h3", { text: "Starting OpenCode..." });
    statusContainer.createEl("p", {
      text: "Please wait while the server starts up.",
      cls: "opencode-status-message"
    });
  }
  renderRunningState() {
    this.contentEl.empty();
    const headerEl = this.contentEl.createDiv({ cls: "opencode-header" });
    const titleSection = headerEl.createDiv({ cls: "opencode-header-title" });
    const iconEl = titleSection.createSpan();
    (0, import_obsidian2.setIcon)(iconEl, OPENCODE_ICON_NAME);
    titleSection.createSpan({ text: "OpenCode" });
    const actionsEl = headerEl.createDiv({ cls: "opencode-header-actions" });
    const reloadButton = actionsEl.createEl("button", {
      attr: { "aria-label": "Reload" }
    });
    (0, import_obsidian2.setIcon)(reloadButton, "refresh-cw");
    reloadButton.addEventListener("click", () => {
      this.reloadIframe();
    });
    const stopButton = actionsEl.createEl("button", {
      attr: { "aria-label": "Stop server" }
    });
    (0, import_obsidian2.setIcon)(stopButton, "square");
    stopButton.addEventListener("click", () => {
      this.plugin.stopServer();
    });
    const iframeContainer = this.contentEl.createDiv({
      cls: "opencode-iframe-container"
    });
    console.log("[OpenCode] Loading iframe with URL:", this.plugin.getServerUrl());
    this.iframeEl = iframeContainer.createEl("iframe", {
      cls: "opencode-iframe",
      attr: {
        src: this.plugin.getServerUrl(),
        frameborder: "0",
        allow: "clipboard-read; clipboard-write"
      }
    });
    this.iframeEl.addEventListener("error", () => {
      console.error("Failed to load OpenCode iframe");
    });
  }
  renderErrorState() {
    this.contentEl.empty();
    const statusContainer = this.contentEl.createDiv({
      cls: "opencode-status-container opencode-error"
    });
    const iconEl = statusContainer.createDiv({ cls: "opencode-status-icon" });
    (0, import_obsidian2.setIcon)(iconEl, "alert-circle");
    statusContainer.createEl("h3", { text: "Failed to start OpenCode" });
    const errorMessage = this.plugin.getLastError();
    if (errorMessage) {
      statusContainer.createEl("p", {
        text: errorMessage,
        cls: "opencode-status-message opencode-error-message"
      });
    } else {
      statusContainer.createEl("p", {
        text: "There was an error starting the OpenCode server.",
        cls: "opencode-status-message"
      });
    }
    const buttonContainer = statusContainer.createDiv({
      cls: "opencode-button-group"
    });
    const retryButton = buttonContainer.createEl("button", {
      text: "Retry",
      cls: "mod-cta"
    });
    retryButton.addEventListener("click", () => {
      this.plugin.startServer();
    });
    const settingsButton = buttonContainer.createEl("button", {
      text: "Open Settings"
    });
    settingsButton.addEventListener("click", () => {
      this.app.setting.open();
      this.app.setting.openTabById("obsidian-opencode");
    });
  }
  renderNotInstalledState() {
    this.contentEl.empty();
    const statusContainer = this.contentEl.createDiv({
      cls: "opencode-status-container"
    });
    const iconEl = statusContainer.createDiv({ cls: "opencode-status-icon" });
    (0, import_obsidian2.setIcon)(iconEl, "download");
    statusContainer.createEl("h3", { text: "OpenCode is not installed" });
    statusContainer.createEl("p", {
      text: "Install OpenCode to use AI-powered coding assistance in Obsidian.",
      cls: "opencode-status-message"
    });
    const installButton = statusContainer.createEl("button", {
      text: "Install OpenCode",
      cls: "mod-cta"
    });
    installButton.addEventListener("click", async () => {
      installButton.disabled = true;
      installButton.textContent = "Installing...";
      await this.plugin.installOpenCode();
      this.onOpen();
    });
    const settingsButton = statusContainer.createEl("button", {
      text: "Open Settings"
    });
    settingsButton.addEventListener("click", () => {
      this.app.setting.open();
      this.app.setting.openTabById("obsidian-opencode");
    });
    statusContainer.createEl("p", {
      text: "Note: This requires Node.js and npm to be installed on your system.",
      cls: "opencode-status-hint"
    });
  }
  reloadIframe() {
    if (this.iframeEl) {
      const src = this.iframeEl.src;
      this.iframeEl.src = "about:blank";
      setTimeout(() => {
        if (this.iframeEl) {
          this.iframeEl.src = src;
        }
      }, 100);
    }
  }
};

// src/SettingsTab.ts
var import_obsidian3 = require("obsidian");
var import_fs = require("fs");
var import_os = require("os");
function expandTilde(path4) {
  if (path4 === "~") {
    return (0, import_os.homedir)();
  }
  if (path4.startsWith("~/")) {
    return path4.replace("~", (0, import_os.homedir)());
  }
  return path4;
}
var OpenCodeSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.validateTimeout = null;
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "OpenCode Settings" });
    containerEl.createEl("h3", { text: "Server Configuration" });
    new import_obsidian3.Setting(containerEl).setName("Port").setDesc("Port number for the OpenCode web server").addText(
      (text) => text.setPlaceholder("14096").setValue(this.plugin.settings.port.toString()).onChange(async (value) => {
        const port = parseInt(value, 10);
        if (!isNaN(port) && port > 0 && port < 65536) {
          this.plugin.settings.port = port;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Hostname").setDesc("Hostname to bind the server to (usually 127.0.0.1)").addText(
      (text) => text.setPlaceholder("127.0.0.1").setValue(this.plugin.settings.hostname).onChange(async (value) => {
        this.plugin.settings.hostname = value || "127.0.0.1";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("OpenCode path").setDesc(
      "Path to the OpenCode executable. Leave as 'opencode' if it's in your PATH."
    ).addText(
      (text) => text.setPlaceholder("opencode").setValue(this.plugin.settings.opencodePath).onChange(async (value) => {
        this.plugin.settings.opencodePath = value || "opencode";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Project directory").setDesc(
      "Override the starting directory for OpenCode. Leave empty to use the vault root. Supports ~ for home directory."
    ).addText(
      (text) => text.setPlaceholder("/path/to/project or ~/project").setValue(this.plugin.settings.projectDirectory).onChange((value) => {
        if (this.validateTimeout) {
          clearTimeout(this.validateTimeout);
        }
        this.validateTimeout = setTimeout(async () => {
          await this.validateAndSetProjectDirectory(value);
        }, 500);
      })
    );
    containerEl.createEl("h3", { text: "Behavior" });
    new import_obsidian3.Setting(containerEl).setName("Auto-start server").setDesc(
      "Automatically start the OpenCode server when Obsidian opens (not recommended for faster startup)"
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoStart).onChange(async (value) => {
        this.plugin.settings.autoStart = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Default view location").setDesc(
      "Where to open the OpenCode panel: sidebar opens in the right panel, main opens as a tab in the editor area"
    ).addDropdown(
      (dropdown) => dropdown.addOption("sidebar", "Sidebar").addOption("main", "Main window").setValue(this.plugin.settings.defaultViewLocation).onChange(async (value) => {
        this.plugin.settings.defaultViewLocation = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "OpenCode Installation" });
    this.renderInstallationSection(containerEl);
    containerEl.createEl("h3", { text: "Server Status" });
    const statusContainer = containerEl.createDiv({ cls: "opencode-settings-status" });
    this.renderServerStatus(statusContainer);
  }
  async validateAndSetProjectDirectory(value) {
    const trimmed = value.trim();
    if (!trimmed) {
      await this.plugin.updateProjectDirectory("");
      return;
    }
    if (!trimmed.startsWith("/") && !trimmed.startsWith("~") && !trimmed.match(/^[A-Za-z]:\\/)) {
      new import_obsidian3.Notice("Project directory must be an absolute path (or start with ~)");
      return;
    }
    const expanded = expandTilde(trimmed);
    try {
      if (!(0, import_fs.existsSync)(expanded)) {
        new import_obsidian3.Notice("Project directory does not exist");
        return;
      }
      const stat = (0, import_fs.statSync)(expanded);
      if (!stat.isDirectory()) {
        new import_obsidian3.Notice("Project directory path is not a directory");
        return;
      }
    } catch (error) {
      new import_obsidian3.Notice(`Failed to validate path: ${error.message}`);
      return;
    }
    await this.plugin.updateProjectDirectory(expanded);
  }
  renderServerStatus(container) {
    container.empty();
    const state = this.plugin.getProcessState();
    const statusText = {
      stopped: "Stopped",
      starting: "Starting...",
      running: "Running",
      error: "Error"
    };
    const statusClass = {
      stopped: "status-stopped",
      starting: "status-starting",
      running: "status-running",
      error: "status-error"
    };
    const statusEl = container.createDiv({ cls: "opencode-status-line" });
    statusEl.createSpan({ text: "Status: " });
    statusEl.createSpan({
      text: statusText[state],
      cls: `opencode-status-badge ${statusClass[state]}`
    });
    if (state === "running") {
      const urlEl = container.createDiv({ cls: "opencode-status-line" });
      urlEl.createSpan({ text: "URL: " });
      const linkEl = urlEl.createEl("a", {
        text: this.plugin.getServerUrl(),
        href: this.plugin.getServerUrl()
      });
      linkEl.addEventListener("click", (e) => {
        e.preventDefault();
        window.open(this.plugin.getServerUrl(), "_blank");
      });
    }
    const buttonContainer = container.createDiv({ cls: "opencode-settings-buttons" });
    if (state === "stopped" || state === "error") {
      const startButton = buttonContainer.createEl("button", {
        text: "Start Server",
        cls: "mod-cta"
      });
      startButton.addEventListener("click", async () => {
        await this.plugin.startServer();
        this.renderServerStatus(container);
      });
    }
    if (state === "running") {
      const stopButton = buttonContainer.createEl("button", {
        text: "Stop Server"
      });
      stopButton.addEventListener("click", () => {
        this.plugin.stopServer();
        this.renderServerStatus(container);
      });
      const restartButton = buttonContainer.createEl("button", {
        text: "Restart Server",
        cls: "mod-warning"
      });
      restartButton.addEventListener("click", async () => {
        this.plugin.stopServer();
        await this.plugin.startServer();
        this.renderServerStatus(container);
      });
    }
    if (state === "starting") {
      buttonContainer.createSpan({
        text: "Please wait...",
        cls: "opencode-status-waiting"
      });
    }
  }
  renderInstallationSection(containerEl) {
    const state = this.plugin.getInstallationState();
    const version = this.plugin.getInstalledVersion();
    const installations = this.plugin.getInstallations();
    const statusText = {
      "not-installed": "Not Installed",
      "installing": "Installing...",
      "installed": "Installed",
      "error": "Error"
    };
    const statusClass = {
      "not-installed": "status-stopped",
      "installing": "status-starting",
      "installed": "status-running",
      "error": "status-error"
    };
    new import_obsidian3.Setting(containerEl).setName("Installation Status").setDesc("Current status of OpenCode installation").addButton((button) => {
      button.setButtonText(statusText[state]).setDisabled(true).buttonEl.addClass(`opencode-status-badge ${statusClass[state]}`);
      return button;
    });
    if (version) {
      new import_obsidian3.Setting(containerEl).setName("Installed Version").setDesc(`OpenCode version ${version} is installed`);
    }
    if (state === "not-installed") {
      new import_obsidian3.Setting(containerEl).setName("Install OpenCode").setDesc("Install OpenCode via npm (requires Node.js and npm)").addButton((button) => {
        button.setButtonText("Install").setCta().onClick(async () => {
          button.setDisabled(true);
          button.setButtonText("Installing...");
          await this.plugin.installOpenCode();
          this.display();
        });
        return button;
      });
    }
    if (installations.length > 0) {
      new import_obsidian3.Setting(containerEl).setName("Active Installation").setDesc("Select which OpenCode installation to use").addDropdown((dropdown) => {
        for (const installation of installations) {
          const label = installation.source === "managed" ? `Managed (${installation.version})` : `System (${installation.version}) - ${installation.executablePath}`;
          dropdown.addOption(installation.id, label);
        }
        dropdown.setValue(this.plugin.settings.selectedInstallationId || installations[0].id).onChange(async (value) => {
          await this.plugin.selectInstallation(value);
          this.display();
        });
        return dropdown;
      });
      const managedInstallations = installations.filter((i) => i.source === "managed");
      if (managedInstallations.length > 0) {
        new import_obsidian3.Setting(containerEl).setName("Managed Installations").setDesc("Uninstall managed OpenCode installations");
        for (const installation of managedInstallations) {
          new import_obsidian3.Setting(containerEl).setName(`Version ${installation.version}`).setDesc(`Installed at ${new Date(installation.installDate).toLocaleString()}`).addButton((button) => {
            button.setButtonText("Uninstall").setWarning().onClick(async () => {
              if (confirm(`Uninstall OpenCode ${installation.version}?`)) {
                await this.plugin.uninstallOpenCode(installation.id);
                this.display();
              }
            });
            return button;
          });
        }
      }
    }
    new import_obsidian3.Setting(containerEl).setName("Auto-install on first run").setDesc("Automatically install OpenCode when no installation is found").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoInstallEnabled).onChange(async (value) => {
        this.plugin.settings.autoInstallEnabled = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Check for updates").setDesc("Periodically check for OpenCode updates").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.checkForUpdates).onChange(async (value) => {
        this.plugin.settings.checkForUpdates = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/ProcessManager.ts
var import_child_process = require("child_process");
var ProcessManager = class {
  constructor(settings, projectDirectory, configPath = null, onStateChange) {
    this.process = null;
    this.state = "stopped";
    this.lastError = null;
    this.earlyExitCode = null;
    this.settings = settings;
    this.projectDirectory = projectDirectory;
    this.configPath = configPath;
    this.onStateChange = onStateChange;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  updateProjectDirectory(directory) {
    this.projectDirectory = directory;
  }
  updateConfigPath(configPath) {
    this.configPath = configPath;
  }
  getState() {
    return this.state;
  }
  getLastError() {
    return this.lastError;
  }
  getUrl() {
    const encodedPath = btoa(unescape(encodeURIComponent(this.projectDirectory)));
    return `http://${this.settings.hostname}:${this.settings.port}/${encodedPath}`;
  }
  async start() {
    var _a, _b;
    if (this.state === "running" || this.state === "starting") {
      return true;
    }
    this.setState("starting");
    this.lastError = null;
    this.earlyExitCode = null;
    if (!this.projectDirectory) {
      return this.setError("Project directory (vault) not configured");
    }
    if (await this.checkServerHealth()) {
      console.log("[OpenCode] Server already running on port", this.settings.port);
      this.setState("running");
      return true;
    }
    console.log("[OpenCode] Starting server:", {
      opencodePath: this.settings.opencodePath,
      port: this.settings.port,
      hostname: this.settings.hostname,
      configPath: this.configPath,
      cwd: this.projectDirectory,
      projectDirectory: this.projectDirectory
    });
    const args = [
      "serve",
      "--port",
      this.settings.port.toString(),
      "--hostname",
      this.settings.hostname,
      "--cors",
      "app://obsidian.md"
    ];
    if (this.configPath) {
      args.push("--config", this.configPath);
    }
    this.process = (0, import_child_process.spawn)(
      this.settings.opencodePath,
      args,
      {
        cwd: this.projectDirectory,
        env: { ...process.env },
        stdio: ["ignore", "pipe", "pipe"],
        detached: false
      }
    );
    console.log("[OpenCode] Process spawned with PID:", this.process.pid);
    (_a = this.process.stdout) == null ? void 0 : _a.on("data", (data) => {
      console.log("[OpenCode]", data.toString().trim());
    });
    (_b = this.process.stderr) == null ? void 0 : _b.on("data", (data) => {
      console.error("[OpenCode Error]", data.toString().trim());
    });
    this.process.on("exit", (code, signal) => {
      console.log(`[OpenCode] Process exited with code ${code}, signal ${signal}`);
      this.process = null;
      if (this.state === "starting" && code !== null && code !== 0) {
        this.earlyExitCode = code;
      }
      if (this.state === "running") {
        this.setState("stopped");
      }
    });
    this.process.on("error", (err) => {
      console.error("[OpenCode] Failed to start process:", err);
      this.process = null;
      if (err.code === "ENOENT") {
        this.setError(`Executable not found at '${this.settings.opencodePath}'`);
      } else {
        this.setError(`Failed to start: ${err.message}`);
      }
    });
    const ready = await this.waitForServerOrExit(this.settings.startupTimeout);
    if (ready) {
      this.setState("running");
      return true;
    }
    if (this.state === "error") {
      return false;
    }
    this.stop();
    if (this.earlyExitCode !== null) {
      return this.setError(`Process exited unexpectedly (exit code ${this.earlyExitCode})`);
    }
    if (!this.process) {
      return this.setError("Process exited before server became ready");
    }
    return this.setError("Server failed to start within timeout");
  }
  stop() {
    if (!this.process) {
      this.setState("stopped");
      return;
    }
    const proc = this.process;
    console.log("[OpenCode] Stopping process with PID:", proc.pid);
    this.setState("stopped");
    this.process = null;
    proc.kill("SIGTERM");
    setTimeout(() => {
      if (proc.exitCode === null && proc.signalCode === null) {
        console.log("[OpenCode] Process still running, sending SIGKILL");
        proc.kill("SIGKILL");
      }
    }, 2e3);
  }
  setState(state) {
    this.state = state;
    this.onStateChange(state);
  }
  setError(message) {
    this.lastError = message;
    console.error("[OpenCode Error]", message);
    this.setState("error");
    return false;
  }
  async checkServerHealth() {
    try {
      const response = await fetch(`${this.getUrl()}/global/health`, {
        method: "GET",
        signal: AbortSignal.timeout(2e3)
      });
      return response.ok;
    } catch (e) {
      return false;
    }
  }
  async waitForServerOrExit(timeoutMs) {
    const startTime = Date.now();
    const pollInterval = 500;
    while (Date.now() - startTime < timeoutMs) {
      if (!this.process) {
        console.log("[OpenCode] Process exited before server became ready");
        return false;
      }
      if (await this.checkServerHealth()) {
        return true;
      }
      await this.sleep(pollInterval);
    }
    return false;
  }
  sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
};

// src/InstallationManager.ts
var fs5 = __toESM(require("fs"));
var path2 = __toESM(require("path"));
var import_crypto = require("crypto");

// src/utils/exec.ts
var import_child_process2 = require("child_process");
var DEFAULT_TIMEOUT = 3e4;
var NPM_INSTALL_TIMEOUT = 3e5;
var VERSION_CHECK_TIMEOUT = 5e3;
async function exec(command, args, options = {}) {
  const { cwd, env = process.env, timeout = DEFAULT_TIMEOUT } = options;
  return new Promise((resolve, reject) => {
    var _a, _b;
    let stdout = "";
    let stderr = "";
    let completed = false;
    const proc = (0, import_child_process2.spawn)(command, args, {
      cwd,
      env: { ...env },
      stdio: ["ignore", "pipe", "pipe"]
    });
    (_a = proc.stdout) == null ? void 0 : _a.on("data", (data) => {
      stdout += data.toString();
    });
    (_b = proc.stderr) == null ? void 0 : _b.on("data", (data) => {
      stderr += data.toString();
    });
    const timer = setTimeout(() => {
      if (completed) return;
      completed = true;
      proc.kill("SIGTERM");
      reject(new Error(`Command timed out after ${timeout}ms`));
    }, timeout);
    const cleanup = () => {
      clearTimeout(timer);
    };
    proc.on("close", (code) => {
      if (completed) return;
      completed = true;
      cleanup();
      resolve({ stdout, stderr, exitCode: code });
    });
    proc.on("error", (err) => {
      if (completed) return;
      completed = true;
      cleanup();
      reject(err);
    });
  });
}
async function execWithProgress(command, args, onStdout, onStderr, options = {}) {
  const { cwd, env = process.env, timeout = NPM_INSTALL_TIMEOUT } = options;
  return new Promise((resolve, reject) => {
    var _a, _b;
    let stdout = "";
    let stderr = "";
    let completed = false;
    const proc = (0, import_child_process2.spawn)(command, args, {
      cwd,
      env: { ...env },
      stdio: ["ignore", "pipe", "pipe"]
    });
    (_a = proc.stdout) == null ? void 0 : _a.on("data", (data) => {
      const text = data.toString();
      stdout += text;
      onStdout == null ? void 0 : onStdout(text);
    });
    (_b = proc.stderr) == null ? void 0 : _b.on("data", (data) => {
      const text = data.toString();
      stderr += text;
      onStderr == null ? void 0 : onStderr(text);
    });
    const timer = setTimeout(() => {
      if (completed) return;
      completed = true;
      proc.kill("SIGTERM");
      reject(new Error(`Command timed out after ${timeout}ms`));
    }, timeout);
    const cleanup = () => {
      clearTimeout(timer);
    };
    proc.on("close", (code) => {
      if (completed) return;
      completed = true;
      cleanup();
      resolve({ stdout, stderr, exitCode: code });
    });
    proc.on("error", (err) => {
      if (completed) return;
      completed = true;
      cleanup();
      reject(err);
    });
  });
}
function parseVersionFromOutput(output) {
  const versionMatch = output.match(/v?(\d+\.\d+\.\d+)/);
  return versionMatch ? versionMatch[1] : null;
}

// src/utils/download.ts
var fs = __toESM(require("fs"));
var path = __toESM(require("path"));
async function fileExists(filePath) {
  try {
    await fs.promises.access(filePath, fs.constants.F_OK);
    return true;
  } catch (e) {
    return false;
  }
}
async function ensureDir(dirPath) {
  try {
    await fs.promises.mkdir(dirPath, { recursive: true });
  } catch (error) {
    if (error.code !== "EEXIST") {
      throw error;
    }
  }
}

// src/platform/index.ts
var import_os2 = require("os");
function getPlatform() {
  const p = (0, import_os2.platform)();
  if (p === "darwin" || p === "win32" || p === "linux") {
    return p;
  }
  throw new Error(`Unsupported platform: ${p}`);
}
function getArch() {
  const a = (0, import_os2.arch)();
  if (a === "x64" || a === "arm64" || a === "ia32") {
    return a;
  }
  throw new Error(`Unsupported architecture: ${a}`);
}
function getExecutableExtension() {
  return getPlatform() === "win32" ? ".exe" : "";
}
async function getPluginDataDir(plugin) {
  const adapter = plugin.app.vault.adapter;
  const vaultPath = adapter.basePath || "";
  const dataDir = `${vaultPath}/.obsidian/plugins/${plugin.manifest.id}/data`;
  return dataDir;
}
function getInstallationsDir(dataDir) {
  return `${dataDir}/installations`;
}
function getConfigDir(dataDir) {
  return `${dataDir}/config`;
}

// src/platform/darwin.ts
var import_child_process3 = require("child_process");
var import_util = require("util");
var fs2 = __toESM(require("fs"));
var execAsync = (0, import_util.promisify)(import_child_process3.exec);
async function detectSystemNpm() {
  try {
    const { stdout } = await execAsync("which npm");
    return stdout.trim();
  } catch (e) {
    return null;
  }
}
function getCommonOpenCodePaths() {
  return [
    // Actual binary paths (prefer these over wrapper scripts)
    "~/node_modules/opencode-ai/bin/opencode",
    "~/.bun/node_modules/opencode-ai/bin/opencode",
    // Wrapper scripts (these require node in PATH)
    "/usr/local/bin/opencode",
    "/opt/homebrew/bin/opencode",
    "~/.local/bin/opencode",
    "~/.bun/bin/opencode",
    "~/node_modules/.bin/opencode"
  ];
}
async function detectExistingOpenCode() {
  try {
    const { stdout } = await execAsync("which opencode");
    const path4 = stdout.trim();
    console.log("[OpenCode] Found via which:", path4);
    return path4;
  } catch (e) {
    console.log("[OpenCode] 'which opencode' failed, checking common paths...");
    for (const p of getCommonOpenCodePaths()) {
      const expanded = p.replace("~", process.env.HOME || "");
      console.log("[OpenCode] Checking path:", expanded);
      if (fs2.existsSync(expanded)) {
        console.log("[OpenCode] Found opencode at:", expanded);
        return expanded;
      }
    }
    console.log("[OpenCode] No opencode found in common paths");
  }
  return null;
}

// src/platform/win32.ts
var import_child_process4 = require("child_process");
var import_util2 = require("util");
var fs3 = __toESM(require("fs"));
var execAsync2 = (0, import_util2.promisify)(import_child_process4.exec);
async function detectSystemNpm2() {
  try {
    const { stdout } = await execAsync2("where npm");
    const lines = stdout.trim().split("\n");
    return lines[0] || null;
  } catch (e) {
    return null;
  }
}
function getCommonOpenCodePaths2() {
  const programFiles = process.env.ProgramFiles || "C:\\Program Files";
  const appData = process.env.APPDATA || "";
  const localAppData = process.env.LOCALAPPDATA || "";
  return [
    `${programFiles}\\OpenCode\\opencode.exe`,
    `${localAppData}\\OpenCode\\opencode.exe`,
    `${appData}\\npm\\opencode.cmd`,
    `${appData}\\npm\\opencode.exe`
  ];
}
async function detectExistingOpenCode2() {
  try {
    const { stdout } = await execAsync2("where opencode");
    const lines = stdout.trim().split("\n");
    if (lines[0]) {
      return lines[0];
    }
  } catch (e) {
    for (const p of getCommonOpenCodePaths2()) {
      if (fs3.existsSync(p)) {
        return p;
      }
    }
  }
  return null;
}

// src/platform/linux.ts
var import_child_process5 = require("child_process");
var import_util3 = require("util");
var fs4 = __toESM(require("fs"));
var execAsync3 = (0, import_util3.promisify)(import_child_process5.exec);
async function detectSystemNpm3() {
  try {
    const { stdout } = await execAsync3("which npm");
    return stdout.trim();
  } catch (e) {
    return null;
  }
}
function getCommonOpenCodePaths3() {
  return [
    "/usr/local/bin/opencode",
    "/usr/bin/opencode",
    "~/.local/bin/opencode",
    "~/node_modules/.bin/opencode",
    "~/.bun/bin/opencode"
  ];
}
async function detectExistingOpenCode3() {
  try {
    const { stdout } = await execAsync3("which opencode");
    return stdout.trim();
  } catch (e) {
    for (const p of getCommonOpenCodePaths3()) {
      const expanded = p.replace("~", process.env.HOME || "");
      if (fs4.existsSync(expanded)) {
        return expanded;
      }
    }
  }
  return null;
}

// src/InstallationManager.ts
function generateId() {
  return Date.now().toString(36) + (0, import_crypto.randomBytes)(8).toString("hex");
}
var InstallationManager = class {
  constructor(plugin) {
    this.state = "not-installed";
    this.installations = [];
    this.selectedInstallationId = null;
    this.stateChangeCallbacks = /* @__PURE__ */ new Set();
    this.progressCallbacks = /* @__PURE__ */ new Set();
    this.plugin = plugin;
    this.dataDir = "";
    this.installationsDir = "";
    this.registryPath = "";
  }
  async initialize() {
    this.dataDir = await getPluginDataDir(this.plugin);
    this.installationsDir = getInstallationsDir(this.dataDir);
    this.registryPath = path2.join(this.dataDir, "registry.json");
    await ensureDir(this.installationsDir);
    await this.loadRegistry();
    await this.detectState();
  }
  getState() {
    return this.state;
  }
  getInstalledVersion() {
    const selected = this.getSelectedInstallation();
    return (selected == null ? void 0 : selected.version) || null;
  }
  getInstallations() {
    return [...this.installations];
  }
  getSelectedInstallation() {
    if (!this.selectedInstallationId) {
      return null;
    }
    return this.installations.find((i) => i.id === this.selectedInstallationId) || null;
  }
  async detectSystemNpm() {
    const platform2 = getPlatform();
    if (platform2 === "darwin") {
      return detectSystemNpm();
    } else if (platform2 === "win32") {
      return detectSystemNpm2();
    } else {
      return detectSystemNpm3();
    }
  }
  async detectExistingInstallations() {
    const platform2 = getPlatform();
    const detections = [];
    let systemPath = null;
    if (platform2 === "darwin") {
      systemPath = await detectExistingOpenCode();
    } else if (platform2 === "win32") {
      systemPath = await detectExistingOpenCode2();
    } else {
      systemPath = await detectExistingOpenCode3();
    }
    if (systemPath) {
      const version = await this.getVersionExecutable(systemPath);
      if (version) {
        detections.push({
          id: generateId(),
          version,
          installDate: (/* @__PURE__ */ new Date()).toISOString(),
          path: path2.dirname(systemPath),
          executablePath: systemPath,
          source: "system",
          platform: platform2,
          arch: getArch()
        });
      }
    }
    return detections;
  }
  async installOpenCode(options = {}) {
    try {
      this.setState("installing");
      this.notifyProgress({ stage: "detecting", message: "Checking environment..." });
      const npmPath = await this.detectSystemNpm();
      if (!npmPath) {
        return {
          success: false,
          error: "npm not found. Please install Node.js from https://nodejs.org/"
        };
      }
      this.notifyProgress({ stage: "downloading", message: "Downloading OpenCode..." });
      const installId = generateId();
      const installDir = path2.join(this.installationsDir, `opencode-${installId}`);
      await ensureDir(installDir);
      this.notifyProgress({
        stage: "installing",
        message: "Installing OpenCode via npm..."
      });
      const platform2 = getPlatform();
      const npmCmd = platform2 === "win32" ? "npm.cmd" : "npm";
      const result = await execWithProgress(
        npmCmd,
        ["install", "--save-dev", "opencode-ai"],
        (stdout) => {
          if (stdout.includes("opencode-ai@")) {
            this.notifyProgress({
              stage: "installing",
              message: "Installing OpenCode package..."
            });
          }
        },
        (stderr) => {
          console.error("[OpenCode Install]", stderr);
        },
        { cwd: installDir, timeout: NPM_INSTALL_TIMEOUT }
      );
      if (result.exitCode !== 0) {
        throw new Error(`npm install failed: ${result.stderr}`);
      }
      const binPath = path2.join(installDir, "node_modules", ".bin");
      const ext = getExecutableExtension();
      const execName = `opencode${ext}`;
      let execPath = path2.join(binPath, execName);
      if (platform2 === "win32") {
        const cmdPath = path2.join(binPath, "opencode.cmd");
        if (await fileExists(cmdPath)) {
          execPath = cmdPath;
        }
      }
      if (!await fileExists(execPath)) {
        throw new Error("Executable not found after installation");
      }
      this.notifyProgress({ stage: "validating", message: "Validating installation..." });
      const version = await this.getVersionExecutable(execPath);
      if (!version) {
        throw new Error("Failed to get version from installed executable");
      }
      const installation = {
        id: installId,
        version,
        installDate: (/* @__PURE__ */ new Date()).toISOString(),
        path: installDir,
        executablePath: execPath,
        source: "managed",
        platform: platform2,
        arch: getArch()
      };
      this.installations.push(installation);
      this.selectedInstallationId = installId;
      await this.saveRegistry();
      this.setState("installed");
      this.notifyProgress({ stage: "done", message: "Installation complete!" });
      return { success: true, installation };
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      this.setState("error");
      this.notifyProgress({ stage: "done", message: `Installation failed: ${errorMessage}` });
      return { success: false, error: errorMessage };
    }
  }
  async uninstallOpenCode(installationId) {
    const installation = this.installations.find((i) => i.id === installationId);
    if (!installation) {
      throw new Error("Installation not found");
    }
    if (installation.source !== "managed") {
      throw new Error("Cannot uninstall system installation");
    }
    await fs5.promises.rm(installation.path, { recursive: true, force: true });
    this.installations = this.installations.filter((i) => i.id !== installationId);
    if (this.selectedInstallationId === installationId) {
      this.selectedInstallationId = null;
    }
    await this.saveRegistry();
    await this.detectState();
  }
  async selectInstallation(installationId) {
    const installation = this.installations.find((i) => i.id === installationId);
    if (!installation) {
      throw new Error("Installation not found");
    }
    this.selectedInstallationId = installationId;
    await this.saveRegistry();
  }
  onStateChange(callback) {
    this.stateChangeCallbacks.add(callback);
    return () => {
      this.stateChangeCallbacks.delete(callback);
    };
  }
  onProgress(callback) {
    this.progressCallbacks.add(callback);
    return () => {
      this.progressCallbacks.delete(callback);
    };
  }
  setState(state) {
    this.state = state;
    for (const callback of this.stateChangeCallbacks) {
      callback(state);
    }
  }
  notifyProgress(progress) {
    for (const callback of this.progressCallbacks) {
      callback(progress);
    }
  }
  async detectState() {
    const selected = this.getSelectedInstallation();
    if (selected) {
      if (await fileExists(selected.executablePath)) {
        this.state = "installed";
      } else {
        this.state = "not-installed";
        this.selectedInstallationId = null;
      }
    } else {
      this.state = "not-installed";
    }
  }
  async loadRegistry() {
    try {
      const data = await fs5.promises.readFile(this.registryPath, "utf-8");
      const registry = JSON.parse(data);
      this.installations = registry.installations || [];
      this.selectedInstallationId = registry.selectedInstallationId || null;
    } catch (error) {
      const err = error;
      if (err.code === "ENOENT") {
        this.installations = [];
        this.selectedInstallationId = null;
      } else {
        console.error("[OpenCode] Failed to load registry:", err);
        this.installations = [];
        this.selectedInstallationId = null;
      }
    }
  }
  async saveRegistry() {
    try {
      const registry = {
        installations: this.installations,
        selectedInstallationId: this.selectedInstallationId
      };
      await fs5.promises.writeFile(
        this.registryPath,
        JSON.stringify(registry, null, 2),
        "utf-8"
      );
    } catch (error) {
      console.error("[OpenCode] Failed to save registry:", error);
      throw new Error(`Failed to save installation registry: ${error.message}`);
    }
  }
  async getVersionExecutable(execPath) {
    try {
      const result = await exec(execPath, ["--version"], { timeout: VERSION_CHECK_TIMEOUT });
      return parseVersionFromOutput(result.stdout);
    } catch (e) {
      return null;
    }
  }
};

// src/OpencodeSettingsManager.ts
var fs6 = __toESM(require("fs"));
var path3 = __toESM(require("path"));
var OpencodeSettingsManager = class {
  constructor(configDir) {
    this.configDir = configDir;
    this.configPath = path3.join(configDir, "opencode.json");
  }
  /**
   * Generate OpenCode config from plugin settings
   */
  generateConfig(settings) {
    const config = {
      server: {
        port: settings.port,
        hostname: settings.hostname
      },
      cors: {
        allowedOrigins: ["app://obsidian.md"]
      }
    };
    return JSON.stringify(config, null, 2);
  }
  /**
   * Write config file to disk
   */
  async writeConfig(settings) {
    await ensureDir(this.configDir);
    const configContent = this.generateConfig(settings);
    await fs6.promises.writeFile(this.configPath, configContent, "utf-8");
    return this.configPath;
  }
  /**
   * Read existing config file
   */
  async readConfig() {
    try {
      const content = await fs6.promises.readFile(this.configPath, "utf-8");
      return JSON.parse(content);
    } catch (e) {
      return null;
    }
  }
  /**
   * Validate config object
   */
  validateConfig(config) {
    if (typeof config !== "object" || config === null) {
      return false;
    }
    const c = config;
    if (c.server !== void 0) {
      if (typeof c.server !== "object" || c.server === null) {
        return false;
      }
      const server = c.server;
      if (server.port !== void 0 && typeof server.port !== "number") {
        return false;
      }
      if (server.hostname !== void 0 && typeof server.hostname !== "string") {
        return false;
      }
    }
    if (c.cors !== void 0) {
      if (typeof c.cors !== "object" || c.cors === null) {
        return false;
      }
      const cors = c.cors;
      if (cors.allowedOrigins !== void 0) {
        if (!Array.isArray(cors.allowedOrigins)) {
          return false;
        }
        if (!cors.allowedOrigins.every((o) => typeof o === "string")) {
          return false;
        }
      }
    }
    return true;
  }
  /**
   * Merge user config with default config
   */
  mergeConfig(userConfig, defaultConfig) {
    return {
      ...defaultConfig,
      ...userConfig,
      server: {
        ...defaultConfig.server,
        ...userConfig.server
      },
      cors: {
        ...defaultConfig.cors,
        ...userConfig.cors
      }
    };
  }
  /**
   * Get the config file path
   */
  getConfigPath() {
    return this.configPath;
  }
  /**
   * Check if config file exists
   */
  async configExists() {
    try {
      await fs6.promises.access(this.configPath, fs6.constants.F_OK);
      return true;
    } catch (e) {
      return false;
    }
  }
  /**
   * Delete config file
   */
  async deleteConfig() {
    await fs6.promises.rm(this.configPath, { force: true });
  }
};

// src/main.ts
var OpenCodePlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.opencodeSettingsManager = null;
    this.stateChangeCallbacks = [];
  }
  async onload() {
    console.log("Loading OpenCode plugin");
    registerOpenCodeIcons();
    await this.loadSettings();
    this.installationManager = new InstallationManager(this);
    await this.installationManager.initialize();
    const dataDir = await getPluginDataDir(this);
    const configDir = getConfigDir(dataDir);
    this.opencodeSettingsManager = new OpencodeSettingsManager(configDir);
    const selectedInstallation = this.installationManager.getSelectedInstallation();
    if (selectedInstallation) {
      console.log("[OpenCode] Using selected installation:", selectedInstallation.executablePath);
      this.settings.opencodePath = selectedInstallation.executablePath;
      this.settings.installations = this.installationManager.getInstallations();
      this.settings.selectedInstallationId = selectedInstallation.id;
      this.settings.opencodeConfigPath = this.opencodeSettingsManager.getConfigPath();
    } else {
      console.log("[OpenCode] No selected installation, detecting existing installations...");
      const detected = await this.installationManager.detectExistingInstallations();
      console.log("[OpenCode] Detected installations:", detected);
      if (detected.length > 0) {
        this.settings.installations = detected;
        this.settings.opencodePath = detected[0].executablePath;
        await this.saveSettings();
        console.log("[OpenCode] Saved detected opencode path:", detected[0].executablePath);
      } else {
        console.log("[OpenCode] No existing installations detected. Please install OpenCode or check the opencodePath setting.");
      }
    }
    console.log("[OpenCode] Final opencodePath:", this.settings.opencodePath);
    const projectDirectory = this.getProjectDirectory();
    this.processManager = new ProcessManager(
      this.settings,
      projectDirectory,
      this.settings.opencodeConfigPath,
      (state) => this.notifyStateChange(state)
    );
    console.log("[OpenCode] Configured with project directory:", projectDirectory);
    this.registerView(OPENCODE_VIEW_TYPE, (leaf) => new OpenCodeView(leaf, this));
    this.addSettingTab(new OpenCodeSettingTab(this.app, this));
    this.addRibbonIcon(OPENCODE_ICON_NAME, "OpenCode", () => {
      this.activateView();
    });
    this.addCommand({
      id: "toggle-opencode-view",
      name: "Toggle OpenCode panel",
      callback: () => {
        this.toggleView();
      },
      hotkeys: [
        {
          modifiers: ["Mod", "Shift"],
          key: "o"
        }
      ]
    });
    this.addCommand({
      id: "start-opencode-server",
      name: "Start OpenCode server",
      callback: () => {
        this.startServer();
      }
    });
    this.addCommand({
      id: "stop-opencode-server",
      name: "Stop OpenCode server",
      callback: () => {
        this.stopServer();
      }
    });
    this.addCommand({
      id: "install-opencode",
      name: "Install OpenCode",
      callback: () => {
        this.installOpenCode();
      }
    });
    if (this.settings.autoStart) {
      this.app.workspace.onLayoutReady(async () => {
        await this.startServer();
      });
    }
    console.log("OpenCode plugin loaded");
  }
  async onunload() {
    this.stopServer();
    this.app.workspace.detachLeavesOfType(OPENCODE_VIEW_TYPE);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.processManager.updateSettings(this.settings);
  }
  // Update project directory and restart server if running
  async updateProjectDirectory(directory) {
    this.settings.projectDirectory = directory;
    await this.saveData(this.settings);
    this.processManager.updateProjectDirectory(this.getProjectDirectory());
    if (this.getProcessState() === "running") {
      this.stopServer();
      await this.startServer();
    }
  }
  getExistingLeaf() {
    const leaves = this.app.workspace.getLeavesOfType(OPENCODE_VIEW_TYPE);
    return leaves.length > 0 ? leaves[0] : null;
  }
  async activateView() {
    const existingLeaf = this.getExistingLeaf();
    if (existingLeaf) {
      this.app.workspace.revealLeaf(existingLeaf);
      return;
    }
    let leaf = null;
    if (this.settings.defaultViewLocation === "main") {
      leaf = this.app.workspace.getLeaf("tab");
    } else {
      leaf = this.app.workspace.getRightLeaf(false);
    }
    if (leaf) {
      await leaf.setViewState({
        type: OPENCODE_VIEW_TYPE,
        active: true
      });
      this.app.workspace.revealLeaf(leaf);
    }
  }
  async toggleView() {
    const existingLeaf = this.getExistingLeaf();
    if (existingLeaf) {
      const isInSidebar = existingLeaf.getRoot() === this.app.workspace.rightSplit;
      if (isInSidebar) {
        const rightSplit = this.app.workspace.rightSplit;
        if (rightSplit && !rightSplit.collapsed) {
          existingLeaf.detach();
        } else {
          this.app.workspace.revealLeaf(existingLeaf);
        }
      } else {
        existingLeaf.detach();
      }
    } else {
      await this.activateView();
    }
  }
  async startServer() {
    const success = await this.processManager.start();
    if (success) {
      new import_obsidian4.Notice("OpenCode server started");
    }
    return success;
  }
  stopServer() {
    this.processManager.stop();
    new import_obsidian4.Notice("OpenCode server stopped");
  }
  getProcessState() {
    var _a, _b;
    return (_b = (_a = this.processManager) == null ? void 0 : _a.getState()) != null ? _b : "stopped";
  }
  getLastError() {
    var _a;
    return (_a = this.processManager.getLastError()) != null ? _a : null;
  }
  getServerUrl() {
    return this.processManager.getUrl();
  }
  onProcessStateChange(callback) {
    this.stateChangeCallbacks.push(callback);
    return () => {
      const index = this.stateChangeCallbacks.indexOf(callback);
      if (index > -1) {
        this.stateChangeCallbacks.splice(index, 1);
      }
    };
  }
  notifyStateChange(state) {
    for (const callback of this.stateChangeCallbacks) {
      callback(state);
    }
  }
  getProjectDirectory() {
    if (this.settings.projectDirectory) {
      console.log("[OpenCode] Using project directory from settings:", this.settings.projectDirectory);
      return this.settings.projectDirectory;
    }
    const adapter = this.app.vault.adapter;
    const vaultPath = adapter.basePath || "";
    if (!vaultPath) {
      console.warn("[OpenCode] Warning: Could not determine vault path");
    }
    console.log("[OpenCode] Using vault path as project directory:", vaultPath);
    return vaultPath;
  }
  // Installation management methods
  getInstallationState() {
    var _a, _b;
    return (_b = (_a = this.installationManager) == null ? void 0 : _a.getState()) != null ? _b : "not-installed";
  }
  getInstalledVersion() {
    var _a, _b;
    return (_b = (_a = this.installationManager) == null ? void 0 : _a.getInstalledVersion()) != null ? _b : null;
  }
  getInstallations() {
    var _a, _b;
    return (_b = (_a = this.installationManager) == null ? void 0 : _a.getInstallations()) != null ? _b : [];
  }
  async installOpenCode() {
    const result = await this.installationManager.installOpenCode({
      onProgress: (progress) => {
        console.log("[OpenCode Install]", progress.stage, progress.message);
        new import_obsidian4.Notice(`OpenCode: ${progress.message}`);
      }
    });
    if (result.success && result.installation) {
      this.settings.installations = this.installationManager.getInstallations();
      this.settings.selectedInstallationId = result.installation.id;
      this.settings.opencodePath = result.installation.executablePath;
      await this.saveSettings();
      new import_obsidian4.Notice("OpenCode installed successfully!");
    } else if (result.error) {
      new import_obsidian4.Notice(`Installation failed: ${result.error}`);
    }
  }
  async selectInstallation(installationId) {
    await this.installationManager.selectInstallation(installationId);
    const selected = this.installationManager.getSelectedInstallation();
    if (selected) {
      this.settings.opencodePath = selected.executablePath;
      this.settings.selectedInstallationId = selected.id;
      await this.saveSettings();
      if (this.getProcessState() === "running") {
        this.stopServer();
        await this.startServer();
      }
    }
  }
  async uninstallOpenCode(installationId) {
    await this.installationManager.uninstallOpenCode(installationId);
    this.settings.installations = this.installationManager.getInstallations();
    if (this.settings.selectedInstallationId === installationId) {
      this.settings.selectedInstallationId = null;
      const installations = this.installationManager.getInstallations();
      if (installations.length > 0) {
        this.settings.selectedInstallationId = installations[0].id;
        this.settings.opencodePath = installations[0].executablePath;
      }
    }
    await this.saveSettings();
  }
  getInstallationManager() {
    return this.installationManager;
  }
  getOpencodeSettingsManager() {
    return this.opencodeSettingsManager;
  }
};
